apiVersion: v1
kind: ConfigMap
metadata:
  name: deploying-microservice-configmap
  namespace: {{ENV}}
data:
  APP_ENV: "{{ENV}}"
  LOG_LEVEL: "debug"
  MESSAGE: "Welcome to Kubernetes"
  index.php: |
    <?php
    $start = microtime(true);
    while (microtime(true) - $start < 1.0) {
      sqrt(rand());
    }
    echo "Generating CPU load!";
    ?>
---
apiVersion: v1
kind: Secret
metadata:
  name: deploying-microservice-secrets
  namespace: {{ENV}}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "{{AWS_ACCESS_KEY_ID}}"
  AWS_SECRET_ACCESS_KEY: "{{AWS_SECRET_ACCESS_KEY}}"
