apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deploying-microservice-horizontalpodautoscaler
  namespace: {{ENV}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploying-microservice
  minReplicas: {{REPLICA_COUNT}}
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
    scaleDown:
      stabilizationWindowSeconds: 0
