apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ENV}}
  name: app-resource-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-resource-reader-binding
  namespace: {{ENV}}
subjects:
- kind: ServiceAccount
  name: app-service-account
  namespace: {{ENV}}
roleRef:
  kind: Role
  name: app-resource-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: {{ENV}}
